# Generated by Django 4.1.7 on 2023-05-17 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccioon', models.TextField(max_length=150, verbose_name='direccion')),
                ('credenciales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='credenciales')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuario',
                'db_table': 'usuario',
            },
        ),
    ]
