# Generated by Django 4.1.7 on 2023-05-17 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='direccioon',
            new_name='direccion',
        ),
    ]
