# Generated by Django 4.1.7 on 2023-05-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('precio_unitario', models.IntegerField(verbose_name='precio_unitario')),
                ('detalle_producto', models.CharField(max_length=200, verbose_name='detalle_producto')),
            ],
        ),
    ]
