# Generated by Django 4.1.7 on 2023-05-02 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.producto')),
            ],
        ),
    ]
