# Generated by Django 4.1.7 on 2023-05-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_rename_direccioon_usuario_direccion'),
        ('cliente', '0004_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('valor', models.IntegerField(verbose_name='valor')),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.producto')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.usuario')),
            ],
        ),
    ]
