# Generated by Django 4.1.7 on 2023-05-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_rename_estado_carrito_compra_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito_compra',
            old_name='activo',
            new_name='estado',
        ),
    ]
