# Generated by Django 4.1.7 on 2023-05-23 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_venta_detalle_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='fk_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 5, 23, 16, 13, 59, 723867), verbose_name='fecha'),
        ),
    ]
